def help():
    print("Pythem to system wyłącznie w konsoli. Polega na wpisywaniu różnych komend do terminala,")
    print("więc, żeby go używać potrzeba znajomość komend z Pythem'a. Oto one:")
    print()
    print("     useradd - tworzy nowego użytkownika;")
    print()
    print("     print_users - wypisuje wszystkich użytkowników;")
    print()
    print("     log - loguje się do stworzonego wcześniej konta;")
    print()
    print("     whoami - wypisuje obecną nazwę użytkownika;")
    print()
    print("     deluser - usuwa użytkownika;")
    print()
    print(
        "     pycal - oblicza podane liczby. Najpierw trzeba wpisać dwie liczby, a potem wybrać z następujących znaków: + - * / % ^;")
    print()
    print("     txt - tworzy nowy plik tekstowy (żeby z niego wyjść trzeba wpisać exit_txt);")
    print()
    print("     print_txt - wypisuje zawartość pliku tekstowego;")
    print()
    print("     change_password - zmienia hasło obecnego użytkownika;")
    print()
    print("     change_username - zmienia imię obecnego użytkownika;")
    print()
    print(
        "     pymail - otwiera pocztę elektroniczą Pymail. Uwaga! nazwa użytkownika w ['nazwa'] oznacza, że użytkownik już nie istnieje!;")
    print()
    print("     games - włącza terminalowe gry;")
    print()
    print("     time - pokazuje czas;")
    print()
    print("     help - wypisuje wszystkie komendy wraz z wyjaśnieniami;")
    print()
    print("     exit - przełącza system w tryb uśpienia;")